### ISSUE TITLE
Improving examples

### ISSUE THREAD

**Issue by Oostwegel** [adafruit/Adafruit_CircuitPython_BusDevice#52]
Can anyone extend the examples (like smbus2).

- How to write values to a specific registry?
- How to read values from a specific registry?

```
from smbus2 import SMBus

with SMBus(1) as bus:
    # Write a block of 8 bytes to address 80 from offset 0
    data = [1, 2, 3, 4, 5, 6, 7, 8]
    bus.write_i2c_block_data(80, 0, data)
```

```
from smbus2 import SMBus

with SMBus(1) as bus:
    # Read a block of 16 bytes from address 80, offset 0
    block = bus.read_i2c_block_data(80, 0, 16)
    # Returned value is a list of 16 bytes
    print(block)
```

**Comment by siddacious** [comment]
In case it wasn't clear, this is not the repo for the smbus2 library.

I don't fully understand your request, however this library and CircuitPython in general do not support SMBus explicitly, though `I2CDevice` may be able to be used with some sensors because the protocols are very similar.

You can find examples of using BusDevice in the code for the [Register library](https://github.com/adafruit/Adafruit_CircuitPython_Register)

Additionally, most if not all of the CircuitPython libraries for I2C sensors are using `I2CDevice`. You can find links to them here:
https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html#motion-sensors
